export const review = [
	{
		id: 1,
		review: 'I never imagined that LinkedIn would be the key to unlocking my dream job',
		name: 'Marielle Aleksandrev',
		worksin: 'Livetube',
		position: 'Research Associate',
	},
	{
		id: 2,
		review: 'Using LinkedIn helped me connect with industry leaders and land my ideal role',
		name: 'John Doe',
		worksin: 'TechWorld',
		position: 'Software Engineer',
	},
	{
		id: 3,
		review: "LinkedIn's network gave me the opportunity to grow professionally and personally",
		name: 'Sarah Miller',
		worksin: 'DataAnalytics Corp',
		position: 'Data Scientist',
	},
	{
		id: 4,
		review: "I found my dream job through LinkedIn's job recommendations and network",
		name: 'Carlos Sanchez',
		worksin: 'Creative Labs',
		position: 'Marketing Manager',
	},
	{
		id: 5,
		review: 'Thanks to LinkedIn, I connected with the right people and secured a high-paying job',
		name: 'Emily Roberts',
		worksin: 'DesignWorks',
		position: 'UX Designer',
	},
	{
		id: 6,
		review: 'LinkedIn opened doors that led me to a successful career transition',
		name: 'Michael Brown',
		worksin: 'HealthTech Solutions',
		position: 'Product Manager',
	},
	{
		id: 7,
		review: 'The professional connections I made on LinkedIn have been invaluable to my career growth',
		name: 'Olivia Harris',
		worksin: 'FinTech Innovations',
		position: 'Financial Analyst',
	},
	{
		id: 8,
		review: "I landed my first job out of college thanks to LinkedIn's powerful networking tools",
		name: 'James Walker',
		worksin: 'Retail Innovators',
		position: 'Business Development Associate',
	},
	{
		id: 9,
		review: 'LinkedIn helped me refine my personal brand, making me more marketable to employers',
		name: 'Isabella Clark',
		worksin: 'SmartTech Solutions',
		position: 'Web Developer',
	},
	{
		id: 10,
		review: "I was able to get the perfect job match through LinkedIn's advanced search filters",
		name: 'Liam Williams',
		worksin: 'MediaGenius',
		position: 'Content Strategist',
	},
	{
		id: 11,
		review: "LinkedIn's job search feature was exactly what I needed to find my next opportunity",
		name: 'Chloe Turner',
		worksin: 'DataSync',
		position: 'Software Developer',
	},
	{
		id: 12,
		review: 'Thanks to LinkedIn, I am now leading a team of developers at a top tech firm',
		name: 'Ethan Jackson',
		worksin: 'CyberCore',
		position: 'Lead Developer',
	},
	{
		id: 13,
		review: 'The recommendations on LinkedIn helped me secure a position with a top financial company',
		name: 'Sophia Adams',
		worksin: 'Capital Partners',
		position: 'Investment Analyst',
	},
	{
		id: 14,
		review: 'LinkedIn helped me build a strong professional network and find a job in my field',
		name: 'Lucas Smith',
		worksin: 'Marketing Experts',
		position: 'SEO Specialist',
	},
	{
		id: 15,
		review: 'With LinkedIn, I connected with a recruiter who guided me to my dream position',
		name: 'Mia Lee',
		worksin: 'TechWave',
		position: 'UI/UX Designer',
	},
	{
		id: 16,
		review: "I am so grateful for the career-changing connections I've made through LinkedIn",
		name: 'Jacob Thompson',
		worksin: 'Innovative Solutions',
		position: 'Project Manager',
	},
	{
		id: 17,
		review: 'LinkedIn helped me to fine-tune my resume and prepare for interviews',
		name: 'Amelia Brown',
		worksin: 'Healthcare Innovations',
		position: 'Clinical Researcher',
	},
	{
		id: 18,
		review: "I couldn't have asked for a better job opportunity than the one I found through LinkedIn",
		name: 'Benjamin Wilson',
		worksin: 'Techtonic',
		position: 'Data Analyst',
	},
	{
		id: 19,
		review: 'Thanks to LinkedIn, I now have an incredible career in data analytics',
		name: 'Ava Johnson',
		worksin: 'Quantify Data',
		position: 'Business Intelligence Analyst',
	},
	{
		id: 20,
		review: 'I’ve built an amazing career thanks to the job postings I found on LinkedIn',
		name: 'Ella Martinez',
		worksin: 'City Technologies',
		position: 'Mobile Developer',
	},
	{
		id: 21,
		review: 'LinkedIn was instrumental in helping me find a role at a company I truly admire',
		name: 'Daniel Hernandez',
		worksin: 'Innovative Systems',
		position: 'Network Engineer',
	},
	{
		id: 22,
		review: 'Thanks to the connections I made on LinkedIn, I was able to expand my career rapidly',
		name: 'Sophia Green',
		worksin: 'AI Technologies',
		position: 'AI Specialist',
	},
	{
		id: 23,
		review: 'LinkedIn made the process of finding my ideal job easy and straightforward',
		name: 'Jack Davis',
		worksin: 'FutureTech',
		position: 'Cloud Engineer',
	},
	{
		id: 24,
		review: 'By using LinkedIn, I received multiple job offers from leading companies',
		name: 'Megan Wright',
		worksin: 'Media Enterprises',
		position: 'Video Producer',
	},
	{
		id: 25,
		review: "LinkedIn's job search and network helped me transition to a completely new career path",
		name: 'William Taylor',
		worksin: 'Logistics Group',
		position: 'Operations Manager',
	},
	{
		id: 26,
		review: 'I owe my current success to the network I built on LinkedIn, which helped me land my dream job',
		name: 'Emily Jones',
		worksin: 'Banking Systems',
		position: 'Financial Analyst',
	},
	{
		id: 27,
		review: 'LinkedIn made finding a job that aligned with my goals and values so much easier',
		name: 'Olivia Martinez',
		worksin: 'Business Tech',
		position: 'Product Designer',
	},
	{
		id: 28,
		review: "I've connected with amazing professionals on LinkedIn who helped me move forward in my career",
		name: 'James Anderson',
		worksin: 'AdTech Solutions',
		position: 'Sales Executive',
	},
	{
		id: 29,
		review: 'LinkedIn’s platform is the best place to find a job that matches both your skills and interests',
		name: 'Charlotte Lee',
		worksin: 'Smart Innovations',
		position: 'Product Manager',
	},
	{
		id: 30,
		review: 'Thanks to LinkedIn, I now work in a dynamic and innovative field that I’m passionate about',
		name: 'Lucas Gonzalez',
		worksin: 'MediaStream',
		position: 'Content Creator',
	},
	{
		id: 31,
		review: 'I was able to build my professional brand and find a fulfilling job thanks to LinkedIn',
		name: 'Ethan Carter',
		worksin: 'Global Enterprises',
		position: 'HR Specialist',
	},
	{
		id: 32,
		review: 'Using LinkedIn helped me secure my first senior role after years of hard work',
		name: 'Isabelle Cooper',
		worksin: 'Retail Tech',
		position: 'Senior Developer',
	},
	{
		id: 33,
		review: "I owe my successful career change to the power of LinkedIn's professional network",
		name: 'Benjamin King',
		worksin: 'Consulting Innovations',
		position: 'Strategy Consultant',
	},
	{
		id: 34,
		review: 'The job I found through LinkedIn was the perfect match for my skills and passions',
		name: 'Lily Perez',
		worksin: 'Tech Logistics',
		position: 'Operations Lead',
	},
	{
		id: 35,
		review: 'I never thought that LinkedIn would lead me to such an exciting career opportunity',
		name: 'Charlotte Walker',
		worksin: 'Health Management',
		position: 'Clinical Research Coordinator',
	},
	{
		id: 36,
		review: "LinkedIn's platform gave me the chance to connect with professionals that changed my life",
		name: 'Aiden Scott',
		worksin: 'Engineering Solutions',
		position: 'Software Architect',
	},
	{
		id: 37,
		review: 'I found an amazing job on LinkedIn that allowed me to use all my skills and grow further',
		name: 'Mason Lee',
		worksin: 'Blockchain Innovations',
		position: 'Blockchain Developer',
	},
	{
		id: 38,
		review: 'With LinkedIn, I was able to find the perfect job that matched both my personal and professional goals',
		name: 'Amelia Wilson',
		worksin: 'AI Consulting',
		position: 'AI Developer',
	},
	{
		id: 39,
		review: 'The job offers I received on LinkedIn were tailored perfectly to my expertise and aspirations',
		name: 'Oliver Taylor',
		worksin: 'Cloud Solutions',
		position: 'Cloud Solutions Architect',
	},
	{
		id: 40,
		review: 'Thanks to LinkedIn, I’m now working in a job that I love with a great team',
		name: 'Ella Walker',
		worksin: 'Retail Tech',
		position: 'Business Analyst',
	},
	{
		id: 41,
		review: 'LinkedIn allowed me to grow my career while connecting with top-tier professionals in my field',
		name: 'Henry Thomas',
		worksin: 'Logistics Solutions',
		position: 'Logistics Manager',
	},
	{
		id: 42,
		review: 'My LinkedIn profile helped me get recruited by one of the top companies in my industry',
		name: 'Abigail Harris',
		worksin: 'Media Enterprises',
		position: 'Creative Director',
	},
	{
		id: 43,
		review: 'I’ve successfully transitioned into a new career thanks to the connections I made on LinkedIn',
		name: 'Megan Adams',
		worksin: 'Design Tech',
		position: 'User Researcher',
	},
	{
		id: 44,
		review: 'Using LinkedIn’s advanced features, I found a job that I truly enjoy and align with',
		name: 'William Johnson',
		worksin: 'Cloud Innovations',
		position: 'Cloud Engineer',
	},
	{
		id: 45,
		review: 'LinkedIn played a major role in helping me find a great job that matches my career goals',
		name: 'Evan Lewis',
		worksin: 'Automated Solutions',
		position: 'Business Developer',
	},
	{
		id: 46,
		review: 'LinkedIn was an essential tool in my job search that led to a role at a prestigious company',
		name: 'Amelia Clark',
		worksin: 'Creative Solutions',
		position: 'Design Engineer',
	},
	{
		id: 47,
		review: 'I connected with professionals from around the world, and it led me to incredible opportunities',
		name: 'Elijah Rodriguez',
		worksin: 'Global Innovations',
		position: 'Global Director',
	},
	{
		id: 48,
		review: 'The LinkedIn community has been invaluable in providing insights and guidance throughout my career journey',
		name: 'Hannah Martinez',
		worksin: 'Data Intelligence',
		position: 'Data Scientist',
	},
	{
		id: 49,
		review: 'I discovered the power of LinkedIn’s job recommendations and secured an ideal role',
		name: 'Logan Miller',
		worksin: 'MediaWorld',
		position: 'Content Editor',
	},
	{
		id: 50,
		review: 'Thanks to LinkedIn, I now work in a position that truly challenges me and helps me grow',
		name: 'Emily Scott',
		worksin: 'Software Innovators',
		position: 'Lead Developer',
	},
	{
		id: 51,
		review: 'LinkedIn has been crucial in advancing my career with personalized job suggestions',
		name: 'Jackson White',
		worksin: 'Retail World',
		position: 'Market Analyst',
	},
	{
		id: 52,
		review: 'I never thought that LinkedIn would help me land such a rewarding career opportunity',
		name: 'Grace Turner',
		worksin: 'Consulting Hub',
		position: 'Strategy Consultant',
	},
	{
		id: 53,
		review: 'LinkedIn allowed me to access a vast network of professionals that helped propel my career',
		name: 'Daniel Lewis',
		worksin: 'Tech Experts',
		position: 'IT Specialist',
	},
	{
		id: 54,
		review: 'LinkedIn was an instrumental part of my job search and helped me secure a fantastic offer',
		name: 'Victoria Thomas',
		worksin: 'Smart Solutions',
		position: 'Product Manager',
	},
	{
		id: 55,
		review: "I leveraged LinkedIn's features to connect with recruiters who helped me find the perfect role",
		name: 'Nathan Johnson',
		worksin: 'Tech Innovators',
		position: 'Software Developer',
	},
	{
		id: 56,
		review: 'Thanks to LinkedIn, I am now employed at one of the best tech companies',
		name: 'Amelia King',
		worksin: 'Tech Corp',
		position: 'AI Engineer',
	},
	{
		id: 57,
		review: 'LinkedIn provided me with the tools to showcase my skills and get noticed by top employers',
		name: 'Jackson Green',
		worksin: 'Business Solutions',
		position: 'Operations Manager',
	},
	{
		id: 58,
		review: "Thanks to LinkedIn's platform, I was able to connect with key professionals and find an amazing role",
		name: 'Charlotte Harris',
		worksin: 'Innovative Designs',
		position: 'Graphic Designer',
	},
	{
		id: 59,
		review: 'My LinkedIn profile opened the door to an exciting and fulfilling career path',
		name: 'George Clark',
		worksin: 'Creative Solutions',
		position: 'Product Designer',
	},
	{
		id: 60,
		review: 'I owe my career growth to LinkedIn, where I connected with mentors who guided me to success',
		name: 'Sophia Walker',
		worksin: 'Tech Strategies',
		position: 'Software Engineer',
	},
	{
		id: 61,
		review: 'Thanks to LinkedIn, I found a perfect match for my skills and was hired within weeks',
		name: 'Olivia Davis',
		worksin: 'Sales Solutions',
		position: 'Sales Executive',
	},
	{
		id: 62,
		review: 'LinkedIn’s platform is essential for anyone serious about networking and job searching',
		name: 'Mason Wright',
		worksin: 'Tech Edge',
		position: 'Backend Developer',
	},
	{
		id: 63,
		review: 'LinkedIn was the catalyst that allowed me to take my career to the next level',
		name: 'Victoria Green',
		worksin: 'Global Business',
		position: 'Operations Lead',
	},
	{
		id: 64,
		review: 'With LinkedIn, I found a job that was the perfect fit for my career aspirations and values',
		name: 'Mia Turner',
		worksin: 'AI Hub',
		position: 'Machine Learning Engineer',
	},
	{
		id: 65,
		review: 'The LinkedIn job search feature provided tailored suggestions that helped me land an ideal role',
		name: 'James Harris',
		worksin: 'Solutions Co.',
		position: 'Product Manager',
	},
	{
		id: 66,
		review: 'LinkedIn’s job search feature made it easy to find and apply to jobs that aligned with my expertise',
		name: 'Sophia Scott',
		worksin: 'AI Systems',
		position: 'AI Specialist',
	},
	{
		id: 67,
		review: 'I couldn’t be happier with the job I found through LinkedIn’s advanced search capabilities',
		name: 'Alexander Brown',
		worksin: 'Tech Future',
		position: 'Software Developer',
	},
	{
		id: 68,
		review: "I found a role that is both fulfilling and challenging thanks to LinkedIn's network",
		name: 'Chloe Wilson',
		worksin: 'Data Innovations',
		position: 'Data Analyst',
	},
	{
		id: 69,
		review: 'LinkedIn connected me with a network of professionals who helped me secure a job in my field',
		name: 'Liam Green',
		worksin: 'Cloud Technologies',
		position: 'Cloud Engineer',
	},
	{
		id: 70,
		review: 'LinkedIn is the best platform for professionals seeking career advancement opportunities',
		name: 'Harper Johnson',
		worksin: 'Retail Solutions',
		position: 'Business Analyst',
	},
	{
		id: 71,
		review: 'Thanks to LinkedIn, I found a job that not only suits my skills but also my career aspirations',
		name: 'Harper Davis',
		worksin: 'TechStart',
		position: 'Product Manager',
	},
	{
		id: 72,
		review: 'LinkedIn helped me find the perfect fit for my career goals and values',
		name: 'James Martinez',
		worksin: 'Creative Studios',
		position: 'Creative Director',
	},
	{
		id: 73,
		review: 'LinkedIn’s job search filters made it easy to find the best opportunities that match my skills',
		name: 'Ava King',
		worksin: 'Retail Industries',
		position: 'Operations Manager',
	},
	{
		id: 74,
		review: 'I never thought LinkedIn could help me make such a significant leap in my career',
		name: 'Mason Perez',
		worksin: 'TechWorks',
		position: 'Web Developer',
	},
	{
		id: 75,
		review: 'I was able to build a network of professionals on LinkedIn that opened doors to career opportunities',
		name: 'Lily Roberts',
		worksin: 'Design Hub',
		position: 'Design Lead',
	},
	{
		id: 76,
		review: "LinkedIn's job recommendations were spot on, and helped me secure an amazing job",
		name: 'Ella Scott',
		worksin: 'AI Innovators',
		position: 'AI Specialist',
	},
	{
		id: 77,
		review: 'LinkedIn opened the door to opportunities I never knew existed and changed my career for the better',
		name: 'Olivia Evans',
		worksin: 'Tech Solutions',
		position: 'Product Manager',
	},
	{
		id: 78,
		review: 'Thanks to LinkedIn, I secured my dream role and have been advancing in my career ever since',
		name: 'Aiden Taylor',
		worksin: 'Healthcare Solutions',
		position: 'Clinical Specialist',
	},
	{
		id: 79,
		review: "LinkedIn's platform helped me find a job that matched my goals and allowed me to grow professionally",
		name: 'Avery Clark',
		worksin: 'Media Networks',
		position: 'Content Producer',
	},
	{
		id: 80,
		review: 'I wouldn’t have landed this job without LinkedIn’s advanced search and networking tools',
		name: 'Lucas Brown',
		worksin: 'Tech Corporation',
		position: 'Cybersecurity Specialist',
	},
	{
		id: 81,
		review: 'I landed a great opportunity with a leading company thanks to LinkedIn’s powerful job matching algorithms',
		name: 'Ava Harris',
		worksin: 'SmartTech Solutions',
		position: 'Software Engineer',
	},
	{
		id: 82,
		review: 'LinkedIn helped me establish an impressive online presence and connect with top employers',
		name: 'Isaac Martin',
		worksin: 'AI Solutions',
		position: 'Machine Learning Engineer',
	},
	{
		id: 83,
		review: 'LinkedIn’s job search and networking features helped me secure a great opportunity in my field',
		name: 'Isabella Carter',
		worksin: 'Business Solutions',
		position: 'Strategy Consultant',
	},
	{
		id: 84,
		review: 'LinkedIn helped me grow my network and secure a position in a prestigious company',
		name: 'James Walker',
		worksin: 'MediaTech',
		position: 'Project Manager',
	},
	{
		id: 85,
		review: 'I found a great job thanks to LinkedIn’s personalized job recommendations',
		name: 'Ava Martinez',
		worksin: 'Tech Solutions',
		position: 'Developer Advocate',
	},
	{
		id: 86,
		review: 'The personalized job search and networking tools on LinkedIn helped me find an amazing opportunity',
		name: 'Jack Clark',
		worksin: 'Business Hub',
		position: 'Product Manager',
	},
	{
		id: 87,
		review: 'Thanks to LinkedIn, I secured a fantastic role and have been growing my career ever since',
		name: 'Lily Taylor',
		worksin: 'Creative Tech',
		position: 'Software Developer',
	},
	{
		id: 88,
		review: 'I am extremely grateful for LinkedIn’s job matching feature, which helped me find my dream role',
		name: 'Elijah White',
		worksin: 'Digital Innovations',
		position: 'UX/UI Designer',
	},
	{
		id: 89,
		review: 'LinkedIn was an essential tool in helping me land a job that aligns perfectly with my career goals',
		name: 'Zoe Green',
		worksin: 'Retail Inc.',
		position: 'Market Research Analyst',
	},
	{
		id: 90,
		review: 'LinkedIn helped me find a job in a growing industry that perfectly fits my skills and aspirations',
		name: 'Lucas Wilson',
		worksin: 'AI Industries',
		position: 'AI Researcher',
	},
	{
		id: 91,
		review: 'I built meaningful connections on LinkedIn that helped me land the perfect role for my career',
		name: 'Charlotte Clark',
		worksin: 'Smart Enterprises',
		position: 'Operations Specialist',
	},
	{
		id: 92,
		review: 'I found an amazing job opportunity through LinkedIn’s advanced search features',
		name: 'Matthew Davis',
		worksin: 'Design Networks',
		position: 'Design Lead',
	},
	{
		id: 93,
		review: 'LinkedIn gave me the tools to connect with industry leaders and land my dream job',
		name: 'Ella Green',
		worksin: 'Business Tech',
		position: 'Sales Director',
	},
	{
		id: 94,
		review: 'Thanks to LinkedIn, I was able to land my dream role at an incredible company',
		name: 'Ethan Taylor',
		worksin: 'Tech Innovations',
		position: 'Data Scientist',
	},
	{
		id: 95,
		review: 'I can’t thank LinkedIn enough for helping me secure the ideal position to further my career',
		name: 'Olivia Clark',
		worksin: 'Consulting Co.',
		position: 'Business Analyst',
	},
	{
		id: 96,
		review: 'LinkedIn’s job search and networking tools helped me find the perfect job opportunity',
		name: 'Aidan Brown',
		worksin: 'AI Industries',
		position: 'AI Engineer',
	},
	{
		id: 97,
		review: 'LinkedIn made it possible for me to find a job that perfectly matches my expertise and career goals',
		name: 'Isabella Harris',
		worksin: 'Creative Studios',
		position: 'Creative Director',
	},
	{
		id: 98,
		review: 'Thanks to LinkedIn, I discovered the job I’ve been searching for and secured a fantastic opportunity',
		name: 'Mason Evans',
		worksin: 'Tech Solutions',
		position: 'Full Stack Developer',
	},
	{
		id: 99,
		review: 'I wouldn’t have found this incredible job without LinkedIn’s personalized job search tools',
		name: 'Amelia Carter',
		worksin: 'AI Networks',
		position: 'AI Researcher',
	},
	{
		id: 100,
		review: "LinkedIn's personalized job recommendations helped me find the ideal role for my career goals",
		name: 'Nathan Green',
		worksin: 'Design Co.',
		position: 'Graphic Designer',
	},
];
